trigger:
  tags:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  # @param oldVersions List of supported versions separated by a comma.
  testAzureSubscription: Test
  testStorageAccountName: stsharedtfregdevdr9z
  testStorageAccountStaticWebsiteUrl: https://${{ variables.testStorageAccountName }}.z6.web.core.windows.net
  gpgKeyId: 07340459D50626C3F6A981F63690A0EF23A00B59
  releaseTag: $(Build.SourceBranchName)

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        sudo apt update
        sudo apt install goreleaser
    displayName: 'Install Dependencies'

  - task: DownloadSecureFile@1
    name: GPGPrivateKey
    inputs:
      secureFile: 'gpg_private_key.asc'
    displayName: 'Retrieve Secrets'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        gpg --import $(GPGPrivateKey.secureFilePath)
    displayName: 'Import GPG Key'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export VERSION="${RELEASE_TAG#*v}"
        goreleaser --skip publish
        # FIXME martin.weise@sequello.com Something is buggy with GPG on Azure DevOps, overwrite bad goreleaser signature
        gpg --batch --yes --output ./dist/terraform-provider-custom_${VERSION}_SHA256SUMS.sig --detach-sign ./dist/terraform-provider-custom_${VERSION}_SHA256SUMS
    env:
      GPG_KEY_ID: '${{ variables.gpgKeyId }}'
      RELEASE_TAG: '${{ variables.releaseTag }}'
    displayName: 'Build Provider Archives'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export VERSION="${RELEASE_TAG#*v}"
        python ./package.py
    env:
      HOST_URL: '${{ variables.testStorageAccountStaticWebsiteUrl }}'
      RELEASE_TAG: '${{ variables.releaseTag }}'
      GPG_KEY_ID: '${{ variables.gpgKeyId }}'
    displayName: 'Package Release'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export VERSION="${RELEASE_TAG#*v}"
        gpg --verify ./dist/terraform-provider-custom_${VERSION}_SHA256SUMS.sig
    env:
      HOST_URL: '${{ variables.testStorageAccountStaticWebsiteUrl }}'
      RELEASE_TAG: '${{ variables.releaseTag }}'
    displayName: 'Verify Release'

  - task: AzureCLI@2
    inputs:
      azureSubscription: '${{ variables.testAzureSubscription }}'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob upload-batch --overwrite true --source ./registry --destination '$web' --destination-path ''  --pattern '*' --account-name '${{ variables.testStorageAccountName }}'
    displayName: 'Deploy to Azure Storage'
